# Generated by Django 4.2.11 on 2024-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactmessage_remove_staffapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='image',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='related_polls', to='app.choice'),
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, default='helolo', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
