# Generated by Django 4.2.11 on 2024-07-31 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 14, 30, 0, 462663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
