# Generated by Django 4.2.11 on 2024-07-31 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vote_timestamp_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
