# Generated by Django 4.2.11 on 2024-07-31 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 15, 49, 28, 962106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'poll')},
        ),
    ]
