# Generated by Django 4.2.11 on 2024-07-31 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vote_user_alter_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.poll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 16, 39, 49, 21296, tzinfo=datetime.timezone.utc)),
        ),
    ]
