# Generated by Django 4.2.11 on 2024-08-02 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_vote_timestamp_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 12, 10, 53, 4556, tzinfo=datetime.timezone.utc)),
        ),
    ]
