# Generated by Django 4.2.11 on 2024-08-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 13, 57, 25, 561106, tzinfo=datetime.timezone.utc)),
        ),
    ]
