# Generated by Django 4.2.11 on 2024-08-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 8, 53, 965767, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
