# Generated by Django 4.2.20 on 2025-04-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_vote_timestamp_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 16, 34, 13, 882585, tzinfo=datetime.timezone.utc)),
        ),
    ]
