# Generated by Django 4.2.20 on 2025-04-25 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Event_images/'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 17, 4, 19, 991063, tzinfo=datetime.timezone.utc)),
        ),
    ]
