# Generated by Django 4.2.20 on 2025-04-25 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_event_profile_image_alter_vote_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 17, 4, 49, 897971, tzinfo=datetime.timezone.utc)),
        ),
    ]
