# Generated by Django 4.2.20 on 2025-04-28 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_poll_options_poll_created_at_poll_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('national', 'National'), ('state', 'State')], max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/images/')),
            ],
            options={
                'ordering': ['state', 'level', 'position'],
            },
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 14, 9, 18, 296160, tzinfo=datetime.timezone.utc)),
        ),
    ]
