# Generated by Django 4.2.20 on 2025-04-30 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_member_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 14, 5, 54, 595671, tzinfo=datetime.timezone.utc)),
        ),
    ]
