# Generated by Django 4.2.20 on 2025-04-30 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 18, 34, 56, 26431, tzinfo=datetime.timezone.utc)),
        ),
    ]
