# Generated by Django 4.2.20 on 2025-05-01 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_staffapplication_admin_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 10, 44, 19, 572413, tzinfo=datetime.timezone.utc)),
        ),
    ]
