# Generated by Django 4.2.20 on 2025-05-01 17:49

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_vote_timestamp_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 17, 49, 1, 58946, tzinfo=datetime.timezone.utc)),
        ),
    ]
