# Generated by Django 4.2.20 on 2025-05-01 18:56

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_announcement_description_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 18, 56, 11, 287324, tzinfo=datetime.timezone.utc)),
        ),
    ]
